version: '3'
services:
  spark-master:
    image: bitnami/spark:latest
    ports:
      - '8080:8080'
      - '7077:7077'
    environment:
      - SPARK_MODE=master
    volumes:
      - ./data:/bitnami/spark/data

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/bitnami/spark/data